import { RecallItem, HazardIngredient } from "@/app/types";

export const mockRecalls: RecallItem[] = [
  {
    id: "RC-2024-001",
    title: "질식 위험으로 인한 유아용 침대 범퍼 긴급 리콜",
    brand: "베이비드림",
    productName: "소프트 침대 범퍼 세트 (흰색/민트)",
    category: "sleeping",
    severity: "critical",
    status: "active",
    recallDate: "2024-03-15",
    affectedUnits: 12400,
    hazardDescription: "끈이 풀릴 경우 영아의 목에 감길 수 있어 질식 위험 존재",
    summary:
      "제품의 고정 끈이 사용 중 분리될 수 있으며, 이로 인해 36개월 미만 영아에게 질식 사고를 유발할 수 있습니다. 즉시 사용을 중단하고 판매처에 반납하세요.",
    source: "한국소비자원",
    sourceUrl: "https://www.kca.go.kr",
    tags: ["질식위험", "침대범퍼", "영아", "긴급"],
  },
  {
    id: "RC-2024-002",
    title: "파라벤 기준치 초과 유아용 로션 리콜",
    brand: "퓨어베이비",
    productName: "유기농 수분 로션 200ml",
    category: "skincare",
    severity: "high",
    status: "active",
    recallDate: "2024-03-10",
    affectedUnits: 8200,
    hazardDescription: "메틸파라벤 함량이 허용 기준치의 2.3배 초과 검출",
    summary:
      "제품에서 허용 기준치를 초과하는 파라벤 성분이 검출되었습니다. 피부 흡수 시 호르몬 교란을 유발할 수 있어 즉시 사용을 중단하세요.",
    source: "식품의약품안전처",
    sourceUrl: "https://www.mfds.go.kr",
    tags: ["파라벤", "스킨케어", "화학성분", "호르몬교란"],
  },
  {
    id: "RC-2024-003",
    title: "작은 부품 탈락 위험 치발기 자발적 리콜",
    brand: "냠냠토이",
    productName: "실리콘 기린 치발기",
    category: "toys",
    severity: "high",
    status: "active",
    recallDate: "2024-03-05",
    affectedUnits: 31500,
    hazardDescription: "귀 부분이 떨어져 영아가 삼킬 수 있는 위험",
    summary:
      "치발기의 귀 장식 부분이 분리될 수 있으며, 분리된 작은 조각은 영아가 삼켜 질식 위험이 있습니다. 제조사가 자발적 리콜을 실시합니다.",
    source: "제조사 자발적 리콜",
    sourceUrl: "https://www.safetykorea.kr",
    tags: ["치발기", "질식위험", "소형부품", "자발적리콜"],
  },
  {
    id: "RC-2024-004",
    title: "납 성분 검출 유아용 장난감 리콜",
    brand: "컬러월드",
    productName: "목제 알파벳 블록 세트",
    category: "toys",
    severity: "critical",
    status: "investigating",
    recallDate: "2024-02-28",
    affectedUnits: 6800,
    hazardDescription: "도료에서 납 성분이 허용 기준치의 4.7배 초과 검출",
    summary:
      "중국산 목제 완구의 표면 도료에서 납이 과다 검출되었습니다. 납은 신경독성 물질로 영유아가 장난감을 입에 넣을 경우 심각한 건강 피해가 발생할 수 있습니다.",
    source: "국가기술표준원",
    sourceUrl: "https://www.kats.go.kr",
    tags: ["납", "중금속", "완구", "도료"],
  },
  {
    id: "RC-2024-005",
    title: "과열 위험으로 인한 유아용 전동 그네 리콜",
    brand: "스윙베이비",
    productName: "자동 전동 그네 DX-500",
    category: "other",
    severity: "medium",
    status: "resolved",
    recallDate: "2024-02-20",
    affectedUnits: 4300,
    hazardDescription: "배터리 과열로 인한 화재 위험",
    summary:
      "특정 환경 조건에서 배터리가 과열될 수 있으며 화재 위험이 있습니다. 제조사는 무료 교체 서비스를 진행 중입니다.",
    source: "한국소비자원",
    sourceUrl: "https://www.kca.go.kr",
    tags: ["화재위험", "배터리", "전동그네", "과열"],
  },
  {
    id: "RC-2024-006",
    title: "포름알데히드 초과 검출 유아 의류 리콜",
    brand: "리틀엔젤",
    productName: "봄 신상 바디수트 3종 세트",
    category: "clothing",
    severity: "high",
    status: "active",
    recallDate: "2024-02-15",
    affectedUnits: 19200,
    hazardDescription: "포름알데히드 함량이 유아 의류 기준치 75ppm의 3배 초과",
    summary:
      "유아 의류에서 피부 자극 및 알레르기를 유발하는 포름알데히드가 기준치의 3배 초과 검출되었습니다. 즉시 착용을 중단하고 환불 신청하세요.",
    source: "국가기술표준원",
    sourceUrl: "https://www.kats.go.kr",
    tags: ["포름알데히드", "유아의류", "알레르기", "피부자극"],
  },
];

export const mockIngredients: HazardIngredient[] = [
  {
    id: "ING-001",
    name: "Parabens",
    koreanName: "파라벤",
    casNumber: "99-76-3",
    riskLevel: "high",
    categories: ["skincare"],
    description:
      "방부제로 사용되는 화학물질로 메틸파라벤, 에틸파라벤, 프로필파라벤 등이 있습니다.",
    healthEffects: ["호르몬 교란", "알레르기 반응", "피부 자극"],
    commonProducts: ["로션", "샴푸", "물티슈"],
    regulations: {
      korea: "0.4% 이하 허용 (단일 성분)",
      eu: "0.4% 이하 허용",
      us: "FDA 규제 기준 없음",
    },
  },
  {
    id: "ING-002",
    name: "Formaldehyde",
    koreanName: "포름알데히드",
    casNumber: "50-00-0",
    riskLevel: "high",
    categories: ["clothing", "toys"],
    description: "방부 및 주름방지 처리에 사용되는 화학물질로 발암성이 확인된 물질입니다.",
    healthEffects: ["피부 자극", "알레르기", "발암 가능성", "호흡기 자극"],
    commonProducts: ["의류", "침구류", "목제 완구"],
    regulations: {
      korea: "유아 의류 75ppm 이하",
      eu: "피부 직접 접촉 의류 75ppm 이하",
      us: "CPSC 규제",
    },
  },
  {
    id: "ING-003",
    name: "Lead (Pb)",
    koreanName: "납",
    riskLevel: "high",
    categories: ["toys", "other"],
    description: "중금속으로 완구의 도료나 소재에서 검출될 수 있으며 신경독성이 강합니다.",
    healthEffects: ["신경 발달 장애", "지적 발달 저해", "빈혈", "신장 손상"],
    commonProducts: ["도료 완구", "액세서리", "구형 페인트"],
    regulations: {
      korea: "완구 도료 90ppm 이하",
      eu: "완구 도료 90ppm 이하",
      us: "CPSC 100ppm 이하",
    },
  },
];
